/*
 * This source code has been generated by blanco Framework.
 */
package blanco.sample;

import blanco.restgenerator.valueobject.ApiGetTelegram;

/**
 * blancoRestのサンプルAPIの応答電文です。
 */
public class GetEnumCodeSampleGetResponse extends ApiGetTelegram {
    /**
     * フィールド [code]
     *
     * 項目の型 [blanco.sample.EnumCode]
     * コード
     */
    private EnumCode fCode;

    /**
     * フィールド [code]のセッターメソッド
     *
     * 項目の型 [blanco.sample.EnumCode]
     * コード
     *
     * @param argCode フィールド[code]に格納したい値
     */
    public void setCode(final EnumCode argCode) {
        this.fCode = argCode;
    }

    /**
     * フィールド[code]のゲッターメソッド
     *
     * 項目の型 [blanco.sample.EnumCode]
     * コード
     *
     * @return フィールド[code]に格納されている値
     */
    public EnumCode getCode() {
        return this.fCode;
    }

    /**
     * フィールド[code]のゲッターメソッド
     *
     * 項目の型 [java.lang.String]
     * コード
     *
     * @return フィールド[code]の型名文字列
     */
    public static String typeCode() {
        return "blanco.sample.EnumCode";
    }

    /**
     * Gets the string representation of this value object.
     *
     * Note that only the shallow range of the object will be toString.
     *
     * @return String representation of a value obejct.
     */
    @Override
    public String toString() {
        java.lang.String buf = "";
        buf = buf + "blanco.sample.GetEnumCodeSampleGetResponse[";
        buf = buf + "code=" +  this.fCode;
        buf = buf + "]";
        return buf;
    }
}
