/*
 * This source code has been generated by blanco Framework.
 */
package blanco.sample;

import blanco.restgenerator.valueobject.ApiGetTelegram;

/**
 * blancoRestのサンプルAPIの要求電文です。
 */
public class GetEnumCodeSampleGetRequest extends ApiGetTelegram {
    /**
     * フィールド [id]
     *
     * 項目の型 [java.lang.Long]
     */
    private Long fId;

    /**
     * フィールド [id]のセッターメソッド
     *
     * 項目の型 [java.lang.Long]
     *
     * @param argId フィールド[id]に格納したい値
     */
    public void setId(final Long argId) {
        this.fId = argId;
    }

    /**
     * フィールド[id]のゲッターメソッド
     *
     * 項目の型 [java.lang.Long]
     *
     * @return フィールド[id]に格納されている値
     */
    public Long getId() {
        return this.fId;
    }

    /**
     * フィールド[id]のゲッターメソッド
     *
     * 項目の型 [java.lang.String]
     *
     * @return フィールド[id]の型名文字列
     */
    public static String typeId() {
        return "java.lang.Long";
    }

    /**
     * Gets the string representation of this value object.
     *
     * Note that only the shallow range of the object will be toString.
     *
     * @return String representation of a value obejct.
     */
    @Override
    public String toString() {
        java.lang.String buf = "";
        buf = buf + "blanco.sample.GetEnumCodeSampleGetRequest[";
        buf = buf + "id=" +  this.fId;
        buf = buf + "]";
        return buf;
    }
}
