/*
 * This source code has been generated by blanco Framework.
 */
package blanco.sample;

import java.util.ArrayList;

import blanco.restgenerator.valueobject.ApiPostTelegram;

/**
 * blancoRestのサンプルAPIの応答電文です。
 */
public class GetTableSample4PostResponse extends ApiPostTelegram {
    /**
     * フィールド [codeMasters]
     *
     * 項目の型 [java.util.ArrayList]
     * コードマスター
     */
    private ArrayList<CodeDefinition2> fCodeMasters;

    /**
     * フィールド [codeMasters]のセッターメソッド
     *
     * 項目の型 [java.util.ArrayList]
     * コードマスター
     *
     * @param argCodeMasters フィールド[codeMasters]に格納したい値
     */
    public void setCodeMasters(final ArrayList<CodeDefinition2> argCodeMasters) {
        this.fCodeMasters = argCodeMasters;
    }

    /**
     * フィールド[codeMasters]のゲッターメソッド
     *
     * 項目の型 [java.util.ArrayList]
     * コードマスター
     *
     * @return フィールド[codeMasters]に格納されている値
     */
    public ArrayList<CodeDefinition2> getCodeMasters() {
        return this.fCodeMasters;
    }

    /**
     * フィールド[codeMasters]のゲッターメソッド
     *
     * 項目の型 [java.lang.String]
     * コードマスター
     *
     * @return フィールド[codeMasters]の型名文字列
     */
    public static String typeCodeMasters() {
        return "java.util.ArrayList<blanco.sample.CodeDefinition2>";
    }

    /**
     * Gets the string representation of this value object.
     *
     * Note that only the shallow range of the object will be toString.
     *
     * @return String representation of a value obejct.
     */
    @Override
    public String toString() {
        java.lang.String buf = "";
        buf = buf + "blanco.sample.GetTableSample4PostResponse[";
        buf = buf + "codeMasters=" +  this.fCodeMasters;
        buf = buf + "]";
        return buf;
    }
}
