/*
 * This source code has been generated by blanco Framework.
 */
package blanco.sample;

import java.util.ArrayList;

import blanco.restgenerator.valueobject.ApiPostTelegram;

/**
 * blancoRestのサンプルAPIの要求電文です。
 */
public class GetTableSample3PostRequest extends ApiPostTelegram {
    /**
     * フィールド [codeNames]
     *
     * 項目の型 [java.util.ArrayList]
     */
    private ArrayList<String> fCodeNames;

    /**
     * フィールド [codeNames]のセッターメソッド
     *
     * 項目の型 [java.util.ArrayList]
     *
     * @param argCodeNames フィールド[codeNames]に格納したい値
     */
    public void setCodeNames(final ArrayList<String> argCodeNames) {
        this.fCodeNames = argCodeNames;
    }

    /**
     * フィールド[codeNames]のゲッターメソッド
     *
     * 項目の型 [java.util.ArrayList]
     *
     * @return フィールド[codeNames]に格納されている値
     */
    public ArrayList<String> getCodeNames() {
        return this.fCodeNames;
    }

    /**
     * フィールド[codeNames]のゲッターメソッド
     *
     * 項目の型 [java.lang.String]
     *
     * @return フィールド[codeNames]の型名文字列
     */
    public static String typeCodeNames() {
        return "java.util.ArrayList<java.lang.String>";
    }

    /**
     * Gets the string representation of this value object.
     *
     * Note that only the shallow range of the object will be toString.
     *
     * @return String representation of a value obejct.
     */
    @Override
    public String toString() {
        java.lang.String buf = "";
        buf = buf + "blanco.sample.GetTableSample3PostRequest[";
        buf = buf + "codeNames=" +  this.fCodeNames;
        buf = buf + "]";
        return buf;
    }
}
