/*
 * This source code has been generated by blanco Framework.
 */
package blanco.sample;

import java.util.ArrayList;

import blanco.restgenerator.valueobject.ApiPostTelegram;

/**
 * blancoRestのサンプルAPIの応答電文です。
 */
public class PostEnumStatusArraySamplePostResponse extends ApiPostTelegram {
    /**
     * フィールド [result]
     *
     * 項目の型 [java.util.ArrayList]
     * 結果
     */
    private ArrayList<String> fResult;

    /**
     * フィールド [result]のセッターメソッド
     *
     * 項目の型 [java.util.ArrayList]
     * 結果
     *
     * @param argResult フィールド[result]に格納したい値
     */
    public void setResult(final ArrayList<String> argResult) {
        this.fResult = argResult;
    }

    /**
     * フィールド[result]のゲッターメソッド
     *
     * 項目の型 [java.util.ArrayList]
     * 結果
     *
     * @return フィールド[result]に格納されている値
     */
    public ArrayList<String> getResult() {
        return this.fResult;
    }

    /**
     * フィールド[result]のゲッターメソッド
     *
     * 項目の型 [java.lang.String]
     * 結果
     *
     * @return フィールド[result]の型名文字列
     */
    public static String typeResult() {
        return "java.util.ArrayList<java.lang.String>";
    }

    /**
     * Gets the string representation of this value object.
     *
     * Note that only the shallow range of the object will be toString.
     *
     * @return String representation of a value obejct.
     */
    @Override
    public String toString() {
        java.lang.String buf = "";
        buf = buf + "blanco.sample.PostEnumStatusArraySamplePostResponse[";
        buf = buf + "result=" +  this.fResult;
        buf = buf + "]";
        return buf;
    }
}
