/*
 * This source code has been generated by blanco Framework.
 */
package blanco.sample;

import java.util.ArrayList;

import blanco.restgenerator.valueobject.ApiPostTelegram;

/**
 * blancoRestのサンプルAPIの要求電文です。
 */
public class PostEnumStatusArraySamplePostRequest extends ApiPostTelegram {
    /**
     * フィールド [status]
     *
     * 項目の型 [java.util.ArrayList]
     */
    private ArrayList<StatusObject> fStatus;

    /**
     * フィールド [status]のセッターメソッド
     *
     * 項目の型 [java.util.ArrayList]
     *
     * @param argStatus フィールド[status]に格納したい値
     */
    public void setStatus(final ArrayList<StatusObject> argStatus) {
        this.fStatus = argStatus;
    }

    /**
     * フィールド[status]のゲッターメソッド
     *
     * 項目の型 [java.util.ArrayList]
     *
     * @return フィールド[status]に格納されている値
     */
    public ArrayList<StatusObject> getStatus() {
        return this.fStatus;
    }

    /**
     * フィールド[status]のゲッターメソッド
     *
     * 項目の型 [java.lang.String]
     *
     * @return フィールド[status]の型名文字列
     */
    public static String typeStatus() {
        return "java.util.ArrayList<blanco.sample.StatusObject>";
    }

    /**
     * Gets the string representation of this value object.
     *
     * Note that only the shallow range of the object will be toString.
     *
     * @return String representation of a value obejct.
     */
    @Override
    public String toString() {
        java.lang.String buf = "";
        buf = buf + "blanco.sample.PostEnumStatusArraySamplePostRequest[";
        buf = buf + "status=" +  this.fStatus;
        buf = buf + "]";
        return buf;
    }
}
