/*
 * This source code has been generated by blanco Framework.
 */
package blanco.restautotest.message;

/**
 * BlancoRestAutotestが利用するメッセージ。
 */
public class BlancoRestAutotestMessage {
    /**
     * A resource bundle class that is used internally to make messages correspond to property files.
     */
    protected final BlancoRestAutotestMessageResourceBundle fBundle = new BlancoRestAutotestMessageResourceBundle();

    /**
     * Gets the string of message definition ID [BlancoRestAutotest] and key [MBVOJI01].
     *
     * No.2:
     * String [クラス名[{0}]のパッケージ名が指定されていません。]
     *
     * @param arg0 Value of the replacement string {0}.
     * @return Message string.
     */
    public String getMbvoji01(final String arg0) {
        if (arg0 == null) {
            throw new IllegalArgumentException("The parameter [arg0] of the method [getMbvoji01] has been given null. However, null cannot be given to this parameter.");
        }

        return "[MBVOJI01] " + fBundle.getMbvoji01(arg0);
    }

    /**
     * Gets the string of message definition ID [BlancoRestAutotest] and key [MBVOJI02].
     *
     * No.3:
     * String [クラス名[{0}]のフィールド[{1}]の型名が指定されていません。]
     *
     * @param arg0 Value of the replacement string {0}.
     * @param arg1 Value of the replacement string {1}.
     * @return Message string.
     */
    public String getMbvoji02(final String arg0, final String arg1) {
        if (arg0 == null) {
            throw new IllegalArgumentException("The parameter [arg0] of the method [getMbvoji02] has been given null. However, null cannot be given to this parameter.");
        }
        if (arg1 == null) {
            throw new IllegalArgumentException("The parameter [arg1] of the method [getMbvoji02] has been given null. However, null cannot be given to this parameter.");
        }

        return "[MBVOJI02] " + fBundle.getMbvoji02(arg0, arg1);
    }

    /**
     * Gets the string of message definition ID [BlancoRestAutotest] and key [MBVOJI03].
     *
     * No.4:
     * String [クラス名[{0}] でフィールド名が指定されていないものがあります。]
     *
     * @param arg0 Value of the replacement string {0}.
     * @return Message string.
     */
    public String getMbvoji03(final String arg0) {
        if (arg0 == null) {
            throw new IllegalArgumentException("The parameter [arg0] of the method [getMbvoji03] has been given null. However, null cannot be given to this parameter.");
        }

        return "[MBVOJI03] " + fBundle.getMbvoji03(arg0);
    }

    /**
     * Gets the string of message definition ID [BlancoRestAutotest] and key [MBVOJI04].
     *
     * No.5:
     * String [クラス名[{0}] フィールド[{1}]の「型」が指定されていません。「型」を指定してください。]
     *
     * @param arg0 Value of the replacement string {0}.
     * @param arg1 Value of the replacement string {1}.
     * @return Message string.
     */
    public String getMbvoji04(final String arg0, final String arg1) {
        if (arg0 == null) {
            throw new IllegalArgumentException("The parameter [arg0] of the method [getMbvoji04] has been given null. However, null cannot be given to this parameter.");
        }
        if (arg1 == null) {
            throw new IllegalArgumentException("The parameter [arg1] of the method [getMbvoji04] has been given null. However, null cannot be given to this parameter.");
        }

        return "[MBVOJI04] " + fBundle.getMbvoji04(arg0, arg1);
    }

    /**
     * Gets the string of message definition ID [BlancoRestAutotest] and key [MBVOJI05].
     *
     * No.6:
     * String [クラス名[{0}] フィールド[{1}]の「デフォルト値({2})」がセットされています。しかし「{3}」はデフォルト値をサポートしません。]
     *
     * @param arg0 Value of the replacement string {0}.
     * @param arg1 Value of the replacement string {1}.
     * @param arg2 Value of the replacement string {2}.
     * @param arg3 Value of the replacement string {3}.
     * @return Message string.
     */
    public String getMbvoji05(final String arg0, final String arg1, final String arg2, final String arg3) {
        if (arg0 == null) {
            throw new IllegalArgumentException("The parameter [arg0] of the method [getMbvoji05] has been given null. However, null cannot be given to this parameter.");
        }
        if (arg1 == null) {
            throw new IllegalArgumentException("The parameter [arg1] of the method [getMbvoji05] has been given null. However, null cannot be given to this parameter.");
        }
        if (arg2 == null) {
            throw new IllegalArgumentException("The parameter [arg2] of the method [getMbvoji05] has been given null. However, null cannot be given to this parameter.");
        }
        if (arg3 == null) {
            throw new IllegalArgumentException("The parameter [arg3] of the method [getMbvoji05] has been given null. However, null cannot be given to this parameter.");
        }

        return "[MBVOJI05] " + fBundle.getMbvoji05(arg0, arg1, arg2, arg3);
    }

    /**
     * Gets the string of message definition ID [BlancoRestAutotest] and key [MBVOJI06].
     *
     * No.7:
     * String [クラス名[{0}] フィールド[{1}]の「総称型({2})」がセットされています。しかし「{3}」は総称型をサポートしません。]
     *
     * @param arg0 Value of the replacement string {0}.
     * @param arg1 Value of the replacement string {1}.
     * @param arg2 Value of the replacement string {2}.
     * @param arg3 Value of the replacement string {3}.
     * @return Message string.
     */
    public String getMbvoji06(final String arg0, final String arg1, final String arg2, final String arg3) {
        if (arg0 == null) {
            throw new IllegalArgumentException("The parameter [arg0] of the method [getMbvoji06] has been given null. However, null cannot be given to this parameter.");
        }
        if (arg1 == null) {
            throw new IllegalArgumentException("The parameter [arg1] of the method [getMbvoji06] has been given null. However, null cannot be given to this parameter.");
        }
        if (arg2 == null) {
            throw new IllegalArgumentException("The parameter [arg2] of the method [getMbvoji06] has been given null. However, null cannot be given to this parameter.");
        }
        if (arg3 == null) {
            throw new IllegalArgumentException("The parameter [arg3] of the method [getMbvoji06] has been given null. However, null cannot be given to this parameter.");
        }

        return "[MBVOJI06] " + fBundle.getMbvoji06(arg0, arg1, arg2, arg3);
    }

    /**
     * Gets the string of message definition ID [BlancoRestAutotest] and key [MBVOJI07].
     *
     * No.8:
     * String [クラス名[{0}] フィールド[{1}] では null は許容しません。]
     *
     * @param arg0 Value of the replacement string {0}.
     * @param arg1 Value of the replacement string {1}.
     * @return Message string.
     */
    public String getMbvoji07(final String arg0, final String arg1) {
        if (arg0 == null) {
            throw new IllegalArgumentException("The parameter [arg0] of the method [getMbvoji07] has been given null. However, null cannot be given to this parameter.");
        }
        if (arg1 == null) {
            throw new IllegalArgumentException("The parameter [arg1] of the method [getMbvoji07] has been given null. However, null cannot be given to this parameter.");
        }

        return "[MBVOJI07] " + fBundle.getMbvoji07(arg0, arg1);
    }

    /**
     * Gets the string of message definition ID [BlancoRestAutotest] and key [MBVOJI08].
     *
     * No.9:
     * String [入出力[{0}] で、親プロパティが継続なのに左隣にプロパティが定義されていません。]
     *
     * @param arg0 Value of the replacement string {0}.
     * @return Message string.
     */
    public String getMbvoji08(final String arg0) {
        if (arg0 == null) {
            throw new IllegalArgumentException("The parameter [arg0] of the method [getMbvoji08] has been given null. However, null cannot be given to this parameter.");
        }

        return "[MBVOJI08] " + fBundle.getMbvoji08(arg0);
    }

    /**
     * Gets the string of message definition ID [BlancoRestAutotest] and key [MBVOJI09].
     *
     * No.10:
     * String [入出力[{0}] で、型[{1}]が定義されていますがそれは存在しません。]
     *
     * @param arg0 Value of the replacement string {0}.
     * @param arg1 Value of the replacement string {1}.
     * @return Message string.
     */
    public String getMbvoji09(final String arg0, final String arg1) {
        if (arg0 == null) {
            throw new IllegalArgumentException("The parameter [arg0] of the method [getMbvoji09] has been given null. However, null cannot be given to this parameter.");
        }
        if (arg1 == null) {
            throw new IllegalArgumentException("The parameter [arg1] of the method [getMbvoji09] has been given null. However, null cannot be given to this parameter.");
        }

        return "[MBVOJI09] " + fBundle.getMbvoji09(arg0, arg1);
    }

    /**
     * Gets the string of message definition ID [BlancoRestAutotest] and key [MBVOJI10].
     *
     * No.11:
     * String [電文クラス[{0}] の情報が存在しません。]
     *
     * @param arg0 Value of the replacement string {0}.
     * @return Message string.
     */
    public String getMbvoji10(final String arg0) {
        if (arg0 == null) {
            throw new IllegalArgumentException("The parameter [arg0] of the method [getMbvoji10] has been given null. However, null cannot be given to this parameter.");
        }

        return "[MBVOJI10] " + fBundle.getMbvoji10(arg0);
    }

    /**
     * Gets the string of message definition ID [BlancoRestAutotest] and key [MBVOJA01].
     *
     * No.14:
     * String [メタディレクトリ[{0}]が存在しません。]
     *
     * @param arg0 Value of the replacement string {0}.
     * @return Message string.
     */
    public String getMbvoja01(final String arg0) {
        if (arg0 == null) {
            throw new IllegalArgumentException("The parameter [arg0] of the method [getMbvoja01] has been given null. However, null cannot be given to this parameter.");
        }

        return "[MBVOJA01] " + fBundle.getMbvoja01(arg0);
    }
}
